[package]
name = "static-site-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
hotwatch = "0.5.0"
pulldown-cmark = "0.13.0"
tokio = { version = "1.46.1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["fs"] }
